Models/ContatoModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SistemaDeContatos.Models
{
	[Table("Tb_Contato")]
	public class ContatoModel
	{
		[Column("Id")]
		public int Id { get; set; }

		[Column("Nome")]
		[Required(ErrorMessage = "Favor inserir o nome !")]
		public string Nome { get; set; }

		[Column("Email")]
        [Required(ErrorMessage = "Favor inserir o e-mail !")]
        public string Email { get; set; }

		[Column("Celular")]
        [Required(ErrorMessage = "Favor inserir o celular !")]
        public string Celular { get; set; }
	}
}

Models/ErrorViewModel.cs
namespace SistemaDeContatos.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/ContatoController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaDeContatos.Models;
using SistemaDeContatos.Repositorio;

namespace SistemaDeContatos.Controllers
{
    public class ContatoController : Controller
    {
        private readonly IContatoRepositorio _contatoRepositorio;
        public ContatoController(IContatoRepositorio contatoRepositorio) {
			_contatoRepositorio = contatoRepositorio;
		}

        public IActionResult Index()
        {
            List<ContatoModel> lista = _contatoRepositorio.BuscarTodos();
            return View(lista);
        }

        public IActionResult CriarContato()
        {
            return View();
        }

        public IActionResult AlterarContato(int id)
        {
          ContatoModel contato = _contatoRepositorio.ListarPorId(id);
            return View(contato);
        }

        public IActionResult ExcluirContato(int id)
        {
            ContatoModel contato = _contatoRepositorio.ListarPorId(id);
            return View(contato);
        }

        [HttpPost]
        public IActionResult CriarContato(ContatoModel contatoModel)
        {
            if (ModelState.IsValid)
            {
                _contatoRepositorio.Adicionar(contatoModel);
                return RedirectToAction("Index");
            }
            else
            {
                return View(contatoModel);
            }

        }

        [HttpPost]
        public IActionResult Alterar(ContatoModel contatoModel)
        {
            _contatoRepositorio.Alterar(contatoModel);
            return RedirectToAction("Index");

        }


        public IActionResult Apagar(int id)
        {
            _contatoRepositorio.Apagar(id);
            return RedirectToAction("Index");
        }


    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaDeContatos.Models;
using System.Diagnostics;

namespace SistemaDeContatos.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Contato/AlterarContato.cshtml
@model ContatoModel

@{
    ViewData["Title"] = "Alterar Contato";
}

<h1 class="text-center">Alterar Contato</h1>

<form asp-controller="Contato" asp-action="Alterar" method="post">

    <input type="hidden" asp-for="Id"/>

    <div class="mb-3">
        <label for="nome" class="form-label">Nome </label>
        <input type="text" asp-for=Nome class="form-control" id="nome" aria-describedby="nomeHelp">
        <div id="nomeHelp" class="form-text">Não deixe os campos em branco !</div>
    </div>
    <div class="mb-3">
        <label for="email" class="form-label">E-mail</label>
        <input type="email" asp-for=Email class="form-control" id="email">
    </div>
    <div class="mb-3">
        <label class="form-label" for="tel">Telefone</label>
        <input type="tel" asp-for=Celular class="form-control" id="telefone">
    </div>
    <button type="submit" class="btn btn-primary">Alterar</button>
</form>
<br />
<a asp-controller="Contato" asp-action="Index"><button class="btn btn-danger">Voltar</button> </a>

Views/Contato/CriarContato.cshtml
@model ContatoModel

@{
    ViewData["Title"] = "Criar Contato";
}

<h1 class="text-center">Criar contato</h1>

<form asp-controller="Contato" asp-action="CriarContato" method="post">
    <div class="mb-3">
        <label for="nome" class="form-label">Nome </label>
        <input type="text" asp-for=Nome class="form-control" id="nome" aria-describedby="nomeHelp">
        @Html.ValidationMessageFor(x => x.Nome)
    </div>
    <div class="mb-3">
        <label for="email" class="form-label">E-mail</label>
        <input type="email" asp-for=Email class="form-control" id="email">
        @Html.ValidationMessageFor(x => x.Email)
    </div>
    <div class="mb-3">
        <label class="form-label" for="tel">Telefone</label>
        <input type="tel" asp-for=Celular class="form-control" id="telefone">
        @Html.ValidationMessageFor(x => x.Celular)
    </div>
    <button type="submit" class="btn btn-primary">Cadastrar</button>
</form>
<br />
<a asp-controller="Contato" asp-action="Index"><button class="btn btn-danger">Voltar</button> </a>

Views/Contato/ExcluirContato.cshtml
@model ContatoModel

@{
	ViewData["Title"] = "Excluir";
}

<div class="text-center">
	<h1>Excluir o contato @Model.Nome da agenda?</h1>
	<a class="btn btn-outline-danger" role="button" asp-controller="Contato" asp-action="Index">Cancelar exclusão</a>
	<a class="btn btn-outline-success" role="button" asp-controller="Contato" asp-action="Apagar" asp-route-id="@Model.Id">Confirmar exclusão</a>
</div>

<a asp-controller="Home" asp-action="Index">Voltar ao início</a>

Views/Contato/Index.cshtml
@model List<ContatoModel>

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Página de contatos !</h1>
    <br />
    <br />
    <a asp-controller="Contato" asp-action="CriarContato"><button type="button" class="btn btn-success btn-lg">Adicionar novo contato</button></a>


</div>

<br />
<br />

<table class="table table-dark table-striped">
    <thead>
        <tr>
            <th scope="col">N° Cadastro</th>
            <th scope="col">Nome</th>
            <th scope="col">E-mail</th>
            <th scope="col">Celular</th>
            <th scope="col"> </th>
        </tr>
    </thead>
    <tbody>

        @if(Model!=null && Model.Any())
        {
            foreach (ContatoModel cm in Model)
            {
                <tr>
                    <th scope="row">@cm.Id</th>
                    <td>@cm.Nome</td>
                    <td>@cm.Email</td>
                    <td>@cm.Celular</td>
                    <td>
                        <div class="btn-group" role="group" aria-label="Basic example">
                            <a asp-controller="Contato" asp-action="AlterarContato" asp-route-id="@cm.Id"><button type="button" class="btn btn-primary">Editar</button></a>
                            <a asp-controller="Contato" asp-action="ExcluirContato" asp-route-id="@cm.Id"><button type="button" class="btn btn-danger">Apagar</button></a>
                        </div>
                    </td>
                </tr>
                
            }   
        }
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bem vindo !!</h1>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sistema De Contatos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SistemaDeContatos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-white bg-black border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sistema De Contatos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Início</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Contato" asp-action="Index">Contatos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SistemaDeContatos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>